### ISSUE TITLE
Update Firefly Jupyterlab Extension

### ISSUE THREAD

**Issue by vandesai1** [nasa-fornax/fornax-images#11]
I believe the General Image already has the Firefly Jupyterlab Extension installed. There is a new version that I would like to use. Can it be updated in the Image?

https://pypi.org/project/jupyter-firefly-extensions/

I understand that this can take some time. I'd love to a demo for someone on Tuesday. Is it possible to install Jupyterlab extensions for just one person?

**Comment by jaladh-singhal** [comment]
Doing 
```bash
conda activate base
pip install --upgrade firefly-client jupyter-firefly-extensions
```

And then reloading browser window makes firefly jupyter extension work! This is of course a one person solution, but it will be best to have both of these packages up-to-date in the image.

**Comment by zoghbi-a** [comment]
@vandesai1. Apologies, I missed this.
This maybe late for the demo, but the image is updated now (Astrophysics Dev Image).
The solution suggested by @jaladh-singhal should do the update between image updates.

**Comment by vandesai1** [comment]
thanks! I was able to do the demo because @jaladh-singhal figured out how to do a temporary install. It wasn't hard, but this is better.

**Comment by jaladh-singhal** [comment]
@zoghbi-a thanks for updating the image. What's the frequency of image update? 

I'm asking this because `firefly-client` and `jupyter-firefly-extensions` are in active development - we roll out new minor releases in every couple of weeks or so. And fornax is a testbed that identifies bugs that we need to fix in firefly-client and friends, so we want fornax to pick up their latest versions as soon as possible.

**Comment by zoghbi-a** [comment]
The way the Fornax system is setup now makes it difficult to make updates to the images. With the new deployment coming up likely by the end of this month, we should be able to do updates more frequently.

**Comment by zoghbi-a** [comment]
Closing as complete as of 11/26/2024
